In [1]:
import torch
import numpy as np

In [3]:
my_list = [[1,2,3,4,5],[6,7,8,9]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9]]

In [19]:
numpy_array = np.array([1,2,3,4,5])
numpy_array
np1 = np.random.rand(3,4,2)
np1
# np1.ndim


array([[[0.20755204, 0.09570806],
        [0.41447367, 0.26884911],
        [0.65330426, 0.09024432],
        [0.03190298, 0.50621423]],

       [[0.41860493, 0.87994158],
        [0.08991399, 0.65326323],
        [0.73798923, 0.59407031],
        [0.89837543, 0.58575551]],

       [[0.01095487, 0.98459829],
        [0.51305469, 0.12177668],
        [0.25828681, 0.15708671],
        [0.8072585 , 0.71654494]]])

In [20]:
tensor_2d = torch.randn(3,4,2)
tensor_2d

tensor([[[ 0.3090,  1.4923],
         [-1.3478,  0.0594],
         [ 1.6779,  0.1027],
         [ 1.3069,  0.7281]],

        [[ 1.6807, -3.4806],
         [-1.0087, -0.5414],
         [ 0.8182, -1.4960],
         [-0.6195, -1.1548]],

        [[ 0.8793,  0.0906],
         [ 0.3464,  0.5369],
         [-0.6556,  0.7568],
         [ 0.6782, -0.1451]]])

In [18]:
tensor_3d = torch.randn(1,2,3)
tensor_3d

tensor([[[-0.4973,  0.2388, -1.4698],
         [ 0.8439, -1.0072,  0.6715]]])

In [23]:
tensor_3d_ = torch.tensor(np1)
tensor_3d_

tensor([[[0.2076, 0.0957],
         [0.4145, 0.2688],
         [0.6533, 0.0902],
         [0.0319, 0.5062]],

        [[0.4186, 0.8799],
         [0.0899, 0.6533],
         [0.7380, 0.5941],
         [0.8984, 0.5858]],

        [[0.0110, 0.9846],
         [0.5131, 0.1218],
         [0.2583, 0.1571],
         [0.8073, 0.7165]]], dtype=torch.float64)

### reshaping and slicing

In [28]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
my_torch = my_torch.reshape(5,2)
my_torch

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [41]:
my2 = torch.arange(14)
my2

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [46]:
my2 = my2.reshape(-1,2)
my2

tensor([[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11],
        [12, 13]])

In [47]:
my3 = torch.arange(10)
my3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
my4 = my3.view(2,-1)
my4
my3[0] = 100
my3
my4

tensor([[100,   1,   2,   3,   4],
        [  5,   6,   7,   8,   9]])

In [56]:
my5= torch.randn(10)
my5


tensor([-0.9115,  1.5651, -0.2718, -1.6004, -0.2213,  0.0112,  0.0982,  0.1165,
         1.0607,  0.7061])

In [57]:
print(my5[0])

tensor(-0.9115)


In [59]:
print(my2[2:4,:])

tensor([[4, 5],
        [6, 7]])
