In [1]:
import torch
import numpy as np

In [6]:
tensor_a = torch.arange(6)
tensor_a = tensor_a.reshape(2,-1)
tensor_b = torch.arange(7,13)
tensor_b = tensor_b.reshape(2,-1)

In [8]:

tensor_b

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [10]:
tensor_a

tensor([[0, 1, 2],
        [3, 4, 5]])

In [11]:
torch.add(tensor_a, tensor_b)

tensor([[ 7,  9, 11],
        [13, 15, 17]])

In [16]:
torch.sub(tensor_b, tensor_a)

tensor([[7, 7, 7],
        [7, 7, 7]])

In [18]:
print(torch .pow(tensor_a, tensor_b))

tensor([[        0,         1,       512],
        [    59049,   4194304, 244140625]])


In [19]:
tensor_a.add_(tensor_b)

tensor([[ 7,  9, 11],
        [13, 15, 17]])

In [20]:
tensor_a

tensor([[ 7,  9, 11],
        [13, 15, 17]])